# Generated by Django 5.1.3 on 2025-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorCd', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('mentorName', models.TextField()),
                ('mentorEmail', models.EmailField(default='default@gmail.com', max_length=254)),
            ],
        ),
    ]
